### ISSUE TITLE
Panic message

### ISSUE THREAD

**Issue by YannCaron** [raphaelthurnherr/algobot_onionOmega#1]
Add a panning message that stop every bot activity.
``` json
{
   "MsgID" : 0,
   "MsgTo" : "algo_2643",
   "MsgFrom" : "MQTTFX",
   "MsgData" : {
      "MsgType" : "command",
      "MsgParam" : "panic"
   }
}
```

**Comment by raphaelthurnherr** [comment]
Use the restart application message for set all devices to OFF.
{
   "MsgID":0,
   "MsgTo":"algo_",
   "MsgFrom":"MQTTFX",
   "MsgData":{
      "MsgType":"command",
      "MsgParam":"system",
      "MsgValue":[
         {
            "application":"restart"
         }
      ]
   }
}
