### ISSUE TITLE
Manage Stream from Command

### ISSUE THREAD

**Issue by YannCaron** [raphaelthurnherr/algobot_onionOmega#13]
Par défaut les Stream doivent être arrêtés.
Une commande doit permettre de les activer et de donnée la frequence (en milliseconds)

**Comment by raphaelthurnherr** [comment]
Function available

``` json
{
   "MsgID":0,
   "MsgTo":"algo_98f8",
   "MsgFrom":"MQTTFX",
   "MsgData":{
      "MsgType":"command",
      "MsgParam":"config",
      "MsgValue":[
         {
            "stream":{
               "state":"off",
               "time":2500,
               "onEvent":"off"
            }
         }
      ]
   }
}
```

For more information, please see:
http://algobot.electool.ch/doku.php?id=communication:mqttmessage#configuration_du_system
