### ISSUE TITLE
What Din left is 0 and Din right is 2 ?

### ISSUE THREAD

**Issue by YannCaron** [raphaelthurnherr/algobot_onionOmega#20]

**Comment by raphaelthurnherr** [comment]
With the Front sensors board, the infrared sensors are connected respectively to DIN0 and DIN2, the DIN1 exist but it is not used with this sensors board.

The Wiki will be update to improve these informations.

http://algobot.electool.ch/doku.php?id=hardwareoverview:algobotmainboard
