### ISSUE TITLE
Create an initialize command

### ISSUE THREAD

**Issue by YannCaron** [raphaelthurnherr/algobot_onionOmega#22]
A command that reset all states (to be sent at the beginning of program, just after connection).

e.g. Set all leds, motors, pwms to off, reset all captors, distance and so on.

**Comment by raphaelthurnherr** [comment]
Use the restart command.

..
   "MsgData":{
      "MsgType":"command",
      "MsgParam":"system",
      "MsgValue":[
         {
            "application":"restart"
         }
      ]
   }
..

**Comment by raphaelthurnherr** [comment]
Also possible to use this config message

...
      "MsgValue":[
         {
            **"config":{
               "reset":"true"
            },**
            "stream":{
               "state":"off",
               "time":1000,
               "onEvent":"off"
            }
         }
      ]
...
