### ISSUE TITLE
Continuous motor commandes

### ISSUE THREAD

**Issue by YannCaron** [raphaelthurnherr/algobot_onionOmega#7]
Add a on/off move command to manage start and stop for motors.

**Comment by raphaelthurnherr** [comment]
When time or cm not specified, the motor run at infinite at the spoecified velocity
In the topic EVENT, only the BEGIN action is sended.
An ABORT message for this infinite action will be reply follow by a BEGIN message after a new command.

**Comment by YannCaron** [comment]
It's works perfectly.... many thanks dude !

![image](https://user-images.githubusercontent.com/5962300/41167840-635f0f62-6b44-11e8-8c83-a2980f4b6adf.png)
